# Generated by Django 5.0.4 on 2024-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="astronomyshow",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_title"
            ),
        ),
    ]
