# Generated by Django 5.0.4 on 2024-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_rename_planetarium_showsession_planetarium_dome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsession',
            name='show_time',
            field=models.DateField(),
        ),
    ]
