# Generated by Django 5.0.4 on 2024-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0004_ticket_unique_row_seats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planetariumdome',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
