# Generated by Django 5.0.4 on 2024-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0005_planetariumdome_unique_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planetariumdome',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='planetariumdome',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_planetarium'),
        ),
        migrations.AddConstraint(
            model_name='showtheme',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
