# Generated by Django 5.0.4 on 2024-05-02 10:55

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0006_remove_planetariumdome_unique_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetariumdome',
            name='image',
            field=models.ImageField(null=True, upload_to=planetarium.models.image_path),
        ),
    ]
