# Generated by Django 5.0.4 on 2024-05-02 12:16

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0008_astronomyshow_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(null=True, upload_to=planetarium.models.astronomy_show_image_path),
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(related_name='astronomy_show', to='planetarium.showtheme'),
        ),
    ]
