# Generated by Django 5.0.4 on 2024-05-02 13:23

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.image_path
            ),
        ),
    ]
